#' Convert an object of class MRMVInput from the MendelianRandomization package to the RMVMR rmvmr_format class
#'
#' Creates a data.frame with additional class `rmvmr_format` from an object of class `MRMVInput` generated by [`MendelianRandomization::mr_mvinput`].
#'
#' @param dat Object from [`MendelianRandomization::mr_mvinput`].
#'
#' @export
#' @return Object of class `rmvmr_format`, the MVMR format
#' @examples
#' bx <- as.matrix(rawdat_rmvmr[,c("ldl_beta", "hdl_beta")])
#' bxse <- as.matrix(rawdat_rmvmr[,c("ldl_se", "hdl_se")])
#' dat <- MendelianRandomization::mr_mvinput(bx = bx,
#'                                           bxse = bxse,
#'                                           by = rawdat_rmvmr$sbp_beta,
#'                                           byse = rawdat_rmvmr$sbp_se,
#'                                           snps = rawdat_rmvmr$snp)
#' dat <- mrmvinput_to_rmvmr_format(dat)
#' head(dat)
#' class(dat)
mrmvinput_to_rmvmr_format <- function(dat) {
  if (!("MRMVInput" %in% class(dat))) {
    stop('The class of the input data object must be "MRMVInput"')
  }

  out <- format_rmvmr(BXGs = dat@betaX,
                      BYG = dat@betaY,
                      seBXGs = dat@betaXse,
                      seBYG = dat@betaYse,
                      RSID = dat@snps)
  out
}
